sudo: required
services:
        - docker

before_install:
        - docker build -t hm3cheun/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true hm3cheun/docker-react npm test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "react-docker"
    env: "ReactDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-831687209203"
    bucket_path: "react-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

        
